/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/qyEmn7cjwSS
 */
import {
  CarouselItem,
  CarouselContent,
  CarouselPrevious,
  CarouselNext,
  Carousel,
} from "@/components/ui/carousel";
import { StackIcon, StarFilledIcon } from "@radix-ui/react-icons";
import Image from "next/image";
import Link from "next/link";

export function FeedBackCarousel() {
  return (
    <div className="flex flex-col gap-y-4 justify-center items-center bg-gradient-to-r from-gray-50 w-full to-gray-100 p-5 space-y-2 ">
      {/* <h2>
        <span className="text-2xl font-bold">Testimonial</span>
      </h2> */}
      <p className="sm:mb-5 bg-gradient-to-r from-blue-600 via-green-500 to-indigo-400 text-transparent bg-clip-text text-center font-bold text-3xl sm:text-5xl leading-tight tracking-tighter">
        Testimonial
      </p>
      <div className="h-1 w-[100%] block sm:hidden rounded-3xl bg-black"></div>
      {/* <h5>Patient Speak</h5> */}
      {/* <h5>Patient Speak</h5> */}
      <div className="min-w-[80%]">
        <div className="flex flex-col gap-y-4 md:flex-row md:justify-evenly items-center">
          <div>
            <p className="font-bold text-xl mg:text-2xl">
              What Our Patient speak
            </p>
          </div>
          <div className="hidden w-1 h-24 md:block rounded-3xl bg-black"></div>
          <div className="flex justify-around items-center">
            <div className="flex flex-col justify-center items-center">
              <div className="text-xs">OverAll Rating</div>
              <div className="font-bold text-green-500 text-3xl">4.5</div>
            </div>
            <div>&nbsp;</div>
            <div>&nbsp;</div>
            <div>&nbsp;</div>
            <div>&nbsp;</div>
            <div className="flex flex-col">
              <div className="flex items-center my-1 space-x-1 text-yellow-400">
                <StarFilledIcon className="w-7 h-7" />
                <StarFilledIcon className="w-7 h-7" />
                <StarFilledIcon className="w-7 h-7" />
                <StarFilledIcon className="w-7 h-7" />
                <StarIcon className="w-7 h-7" />
              </div>
              <Link
                href={"https://g.page/r/CWCle9fHY01uEBI/review"}
                className="text-sm text-blue-700"
              >
                Review us on Google
              </Link>
            </div>
          </div>
        </div>
      </div>
      {/* <div className="w-[60%] h-1 rounded bg-slate-200"></div> */}
      <Carousel className="w-full max-w-[70%] mt-5 sm:max-w-screen-md py-5 ">
        <CarouselContent>
          <CarouselItem>
            <div className="flex flex-col p-2">
              <div className="flex items-center space-x-2">
                <div className="relative rounded-full overflow-hidden w-8 h-8">
                  <Image
                    src="/male1.jpg"
                    alt="1st user review"
                    fill
                    sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                    style={{ objectFit: "cover" }}
                  />
                </div>
                <div className="text-sm font-semibold leading-none">
                  <span className="line-clamp-1">Alice Smith</span>
                </div>
              </div>
              <p className="text-sm text-gray-500 mt-2 leading-snug line-clamp-3">
                &quot;Great experience with the company. The customer service
                was excellent, and the product exceeded my expectations. Highly
                recommended!&quot;
              </p>
              <div className="flex items-center mt-2">
                <div className="flex items-center space-x-1 text-sm text-yellow-500">
                  <StarFilledIcon className="w-4 h-4" />
                  <StarFilledIcon className="w-4 h-4" />
                  <StarFilledIcon className="w-4 h-4" />
                  <StarFilledIcon className="w-4 h-4" />
                  <StarIcon className="w-4 h-4" />
                </div>
              </div>
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="flex flex-col p-2">
              <div className="flex items-center space-x-2">
                <div className="relative rounded-full overflow-hidden w-8 h-8">
                  <Image
                    alt="2nd user review"
                    src="/female1.jpg"
                    fill
                    sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                    style={{ objectFit: "cover" }}
                  />
                </div>
                <div className="text-sm font-semibold leading-none">
                  <span className="line-clamp-1">Martinie</span>
                </div>
              </div>
              <p className="text-sm text-gray-500 mt-2 leading-snug line-clamp-3">
                &quot;The product arrived on time, and it was exactly as
                described. I appreciate the company&apos;s attention to quality
                and customer satisfaction. I will definitely be a returning
                customer.&quot;
              </p>
              <div className="flex items-center mt-2">
                <div className="flex items-center space-x-1 text-sm text-yellow-500">
                  <StarFilledIcon className="w-4 h-4" />
                  <StarFilledIcon className="w-4 h-4" />
                  <StarFilledIcon className="w-4 h-4" />
                  <StarFilledIcon className="w-4 h-4" />
                  <StarFilledIcon className="w-4 h-4" />
                </div>
              </div>
            </div>
          </CarouselItem>
          <CarouselItem>
            <div className="flex flex-col p-2">
              <div className="flex items-center space-x-2">
                <div className="relative rounded-full overflow-hidden w-8 h-8">
                  <Image
                    alt="3rd user review"
                    src="/female2.jpg"
                    fill
                    sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                    style={{ objectFit: "cover" }}
                  />
                </div>
                <div className="text-sm font-semibold leading-none">
                  <span className="line-clamp-1">Claire Williams</span>
                </div>
              </div>
              <p className="text-sm text-gray-500 mt-2 leading-snug line-clamp-3">
                &quot;I encountered an issue with my order, but the support team
                was quick to resolve it. I appreciate the company&apos;s
                dedication to customer satisfaction. The product is fantastic,
                and I am a happy customer.&quot;
              </p>
              <div className="flex items-center mt-2">
                <div className="flex items-center space-x-1 text-sm text-yellow-500">
                  <StarFilledIcon className="w-4 h-4" />
                  <StarFilledIcon className="w-4 h-4" />
                  <StarFilledIcon className="w-4 h-4" />
                  <StarFilledIcon className="w-4 h-4" />
                  <StarIcon className="w-4 h-4" />
                </div>
              </div>
            </div>
          </CarouselItem>
        </CarouselContent>
        <CarouselPrevious />
        <CarouselNext />
        <div />
      </Carousel>
    </div>
  );
}

function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  );
}
